# Generated by Django 3.1.3 on 2020-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('work_day0', models.BooleanField(default=False)),
                ('work_day1', models.BooleanField(default=False)),
                ('work_day2', models.BooleanField(default=False)),
                ('work_day3', models.BooleanField(default=False)),
                ('work_day4', models.BooleanField(default=False)),
                ('work_day5', models.BooleanField(default=False)),
                ('work_day6', models.BooleanField(default=False)),
                ('work_day7', models.BooleanField(default=False)),
                ('work_day8', models.BooleanField(default=False)),
                ('work_day9', models.BooleanField(default=False)),
            ],
        ),
    ]
