# Generated by Django 3.1.3 on 2020-12-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day0',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day1',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day2',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day3',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day4',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day5',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day6',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day7',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day8',
        ),
        migrations.RemoveField(
            model_name='employmodel',
            name='work_day9',
        ),
    ]
