# Generated by Django 3.1.3 on 2020-12-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0002_auto_20201215_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmodel',
            name='work_day0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day9',
            field=models.BooleanField(default=False),
        ),
    ]
