# Generated by Django 3.1.3 on 2020-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0003_auto_20201215_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmodel',
            name='employer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
