# Generated by Django 3.1.3 on 2020-12-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0004_employmodel_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_sheet', models.FileField(upload_to='files/')),
            ],
        ),
    ]
