# Generated by Django 3.1.3 on 2020-12-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0005_shiftmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmodel',
            name='shift_sheet',
            field=models.FileField(upload_to='file/%Y/%m/%d'),
        ),
    ]
