# Generated by Django 3.1.3 on 2021-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0006_auto_20201220_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmodel',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
