# Generated by Django 3.1.3 on 2021-02-27 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0007_employmodel_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftmodel',
            old_name='shift_sheet',
            new_name='upload_dir',
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
