# Generated by Django 3.1.3 on 2021-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0008_auto_20210227_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shiftmodel',
            name='upload_dir',
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='employer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='need_people',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1),
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='times',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='manager',
            field=models.BooleanField(default=True),
        ),
    ]
