# Generated by Django 3.1.3 on 2021-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0009_auto_20210306_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmodel',
            name='work_day10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmodel',
            name='work_day19',
            field=models.BooleanField(default=False),
        ),
    ]
