# Generated by Django 3.1.3 on 2021-03-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0010_auto_20210308_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmodel',
            name='manager',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day0',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day11',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day12',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day13',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day14',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day15',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day16',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day17',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day18',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day19',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day6',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day7',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day8',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employmodel',
            name='work_day9',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
